### ISSUE TITLE
wrong slippage on swap trade

### ISSUE THREAD

**Issue by rui-cruz** [jon4hz/deadshot#9] opened 2022-05-04 23:30 UTC
I used the bot to swap directly because there was an issue with the official frontend, and to play safe before some panic-sell i tried to use the bot.. i added the contracts of the tokens and selected default option mmf for the router. I selected all the assets I had and performed the swap.
The problem was that I had the window small and didnt saw the slippage, witch was 90% and I lost over 10k usd 🤦‍♂️.
I noticed that the swap didnt used the defaut method for swaps on mmf `SwapETHForExactTokens` but instead used `swapExactTokensForTokensSupportingFeeOnTransferTokens`.
Is there a way to specify the methodId on settings?

**Comment by jon4hz** [comment] 2022-05-05 11:21
Hey, was the slippage on 90% by default or did you configure that accidently? Also what tokens did you trade? If you try to swap a token for another token (e.g. mmf -> usdc) you can't use the `swapETHForExactTokens` function.

**Comment by rui-cruz** [comment] 2022-05-06 01:08
No, i didn't set anything besides the contract of the tokens.
I swapped svn and mshare.. I have here a printscreen that fortunately didn't hit "enter" on the MAD token (12$ each at the time)
![image](https://user-images.githubusercontent.com/1080374/167050415-1a69c9f8-2e79-420d-8f2a-8b4136eb3dc3.png)

and this is the transaction
![image](https://user-images.githubusercontent.com/1080374/167050488-add15817-ac03-4863-b086-bec3d5ab4076.png)

**Comment by jon4hz** [comment] 2022-05-06 09:43
I quickly tested the slippage on a swap but unfortunately I couldn't reproduce the error. Could you send me the logs of the bot over email?  (they'll include the tx id and your wallet fyi) 
The logs are located under `~/.config/deadshot/logs/` on linux and `%AppData%\deadshot\logs` on windows. 
Did you experience issues with the slippage on every trade or just this one?

**Comment by rui-cruz** [comment] 2022-05-07 00:25
On 3 trades I mad yes, the slippage was huge, but as I said, the terminal window was small and I didnt noticed :\
[20220504211333.log](https://github.com/jon4hz/deadshot/files/8644115/20220504211333.log)

**Comment by jon4hz** [comment] 2022-05-07 17:17
>  but as I said, the terminal window was small and I didnt noticed
So, I'm a bit confused.. Was the slippage wrong because of some default settings from the bot? -> default slippage should be 1%

**Comment by jon4hz** [comment] 2022-05-07 17:19
> but as I said, the terminal window was small and I didnt noticed  

So, I'm a bit confused.. Was the slippage wrong because of some default settings from the bot? Is there something to be fixed there?
-> default slippage should be 1%

**Comment by jon4hz** [comment] 2022-06-09 09:19
closing this since I'm still not getting an answer if the problem was caused by the user or by the program itself. 
Feel free to comment and I'll reopen it.

**Comment by rui-cruz** [comment] 2022-06-12 21:58
Hi sorry... yes, there is a problem, because the bot used a method on contract what is not the standard on that router, like I said on first comment, it should had used `SwapETHForExactTokens `

**Comment by jon4hz** [comment] 2022-06-12 22:03
I strongly disagree here. `SwapETHForExactTokens` can only be used when you trade ETH (on cronos CRO) for another token. 
Another option would be using `SwapTokensForExactTokens` but that would exclude all tokens that have a dev/marketing/whatever fee (like safemoon e.g.). In order for the bot to be able to trade all these tokens `swapExactTokensForTokensSupportingFeeOnTransferTokens` must be used.

**Comment by rui-cruz** [comment] 2022-06-13 22:42
I'm not aware of other implementations.. I understand your point of view and makes sense.. but on cronos/mmf they use that for all tokens swaps.. you can check here ie [here](https://cronos.org/explorer/tx/0x829fdad976b603ac3767fbdf777a4481e6e0608d28097b4d1fd42ceb19570775/token-transfers)

**Comment by rui-cruz** [comment] 2022-06-13 22:44
You're right.. it should had used `SwapTokensForExactTokens` I can verify on their router [here](https://cronos.org/explorer/address/0x145677FC4d9b8F19B5D56d1820c48e0443049a30/transactions)

**Comment by jon4hz** [comment] 2022-06-13 22:52
Again, not supporting a fee on transfer would exclude all tokens from trading which take a dev fee on each swap. Beside that, `SwapTokensForExactTokens` also requires the configuration of a slippage. So if the wrong slippage wasn't a layer 8 problem, then the error is somewhere else in the code. 
Unfortunately I'm not having the time to look into this in the next few weeks. 
Is this behavior reproducible with order trades or does it only affect swaps?

**Comment by rui-cruz** [comment] 2022-08-07 23:38
Hi, I'm sorry I don't check this email often. I talked to the dex team, and they said I was front-runned (idk what that even really means). Like I said since the beginning, I used all default options, just inserted the tokens and went for swap. Slippage was default 1%, and as I was running on a small window, I did not see the slippage before hit the "enter". 
When I saw what really happened was too late, but that was totally my fault to not tripple-check things... I don't know solidity (yet) and not in position to say what should be used or not, I just said that the dex uses the method `SwapTokensForExactTokens ` and I assumed that the bot should use that too, if not maybe configure somehow.

Thank u

**Comment by jon4hz** [comment] 2022-08-15 13:16
Thanks for the follow up. In that case I will close this again.

**Closed by jon4hz** 2022-08-15 13:16 UTC
Labels: bug

**Comment by rui-cruz** [comment] 2022-08-18 01:19
You can close it, but I think u didn't understand yet.. the team said that I got frontrunned, but before commit the swap the slippage was already 98% instead of the 1% default, so I don't think that was the case.. or am I missing something?
